export const FETCH_PROJECTS = 'project/FETCH_PROJECTS';
export const FETCH_PROJECTS_SUCCESS = 'project/FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAIL = 'project/FETCH_PROJECTS_FAIL';

export const SHOW_ADD_PROJECT_MODAL = 'projects/SHOW_ADD_PROJECT_MODAL';
export const HIDE_ADD_PROJECT_MODAL = 'projects/HIDE_ADD_PROJECT_MODAL';

export const ADD_PROJECT = 'projects/ADD_PROJECT';
export const ADD_PROJECT_SUCCESS = 'projects/ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAIL = 'projects/ADD_PROJECT_FAIL';

export const HANDLE_UPDATE_FORM_LOCATION = 'projects/HANDLE_UPDATE_FORM_LOCATION';
